export const ROUTES = {
  LOGIN: "/",
  DASHBOARD: "/dashboard",
  CREATE_TEST: "/tests/create",
  QUESTIONS: "/tests/:testId/questions",
  PREVIEW: "/tests/:testId/preview",

  ISSUES: "/issues",
  TEST_PAPERS: "/papers",
  USERS: "/users",
  INSTITUTES: "/institutes",
  PROFILE: "/profile",
  ARCHIVE: "/archive",
  PAYMENTS: "/payments",
  LEADERBOARD: "/leaderboard",
  MESSAGES: "/messages",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
  NOT_FOUND: "*",
} as const;
